### ISSUE TITLE
2023年抓取404错误

### ISSUE THREAD

**Issue by lixsh6** [caspiankexin/people-daily-crawler-date#1]
是不是人民日报网页变了的原因，无法按文章抓取了，随便进入一个网页就是404错误：
http://paper.people.com.cn/rmrb/html/2020-01/27/nbs.D110000renmrb_01.htm

**Comment by caspiankexin** [comment]
不是的，人民日报数据库里只能查询近两年的内容，现在就是22年和23年的内容。2年前就不公开了。你这个链接是21年的内容，所以网页就打不开的
