### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xiaoyudemeng** [caspiankexin/people-daily-crawler-date#2]
博主大大你好，那个2024第一个季度的人民日报的资源能不能发一下，那个程序不知道为什么跑了一点点就不跑了（哭）

**Comment by caspiankexin** [comment]
留个邮箱，我晚上发给你

**Comment by xiaoyudemeng** [comment]
博主大大非常感谢，但是我找到问题了，就是有几个广告板块他404了代码过程直接被他中断了，但是也非常感谢971723935@qq.com麻烦博主发一下，谢谢
